/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package manajemen.view;
// Tambahkan import ini di bagian atas file

import manajemen.controller.FutsalController;
import manajemen.model.Lapangan;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class FormManajemenLapangan extends javax.swing.JFrame {

    /**
     * Creates new form FormManajemenLapangan
     */
    public FormManajemenLapangan() {
        initComponents();
        loadDataToTable();  // <--- TAMBAHKAN BARIS INI
    }

    // Letakkan method ini di dalam kelas FormManajemenLapangan
    private void loadDataToTable() {
        // 1. Dapatkan model dari tabel kita yang bernama tblLapangan
        // DefaultTableModel memungkinkan kita memanipulasi data tabel (baris, kolom)
        DefaultTableModel model = new DefaultTableModel();

        // 2. Hapus kolom default dan atur kolom baru yang kita inginkan
        model.addColumn("ID Lapangan");
        model.addColumn("Jenis Lapangan");
        model.addColumn("Ukuran");
        model.addColumn("Harga Sewa / Jam");

        // Set model yang baru ini ke JTable kita
        tblLapangan.setModel(model);

        // 3. Panggil controller untuk mendapatkan semua data lapangan dari database
        FutsalController controller = new FutsalController();
        List<Lapangan> daftarLapangan = controller.getAllLapangan();

        // 4. Looping melalui setiap objek Lapangan di dalam list
        for (Lapangan lap : daftarLapangan) {
            // 5. Buat sebuah baris data (Object array) sesuai urutan kolom
            Object[] rowData = {
                lap.getLapanganId(),
                lap.getJenisLapangan(),
                lap.getUkuran(),
                lap.getHargaSewaPerJam()
            };
            // 6. Tambahkan baris data tersebut ke model tabel
            model.addRow(rowData);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlUtama = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLapangan = new javax.swing.JTable();
        btnTambah = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manajemen Lapangan - Aplikasi Boss Futsal");
        setLocationByPlatform(true);

        pnlUtama.setMinimumSize(new java.awt.Dimension(600, 500));
        pnlUtama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLapangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblLapangan);

        pnlUtama.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, 370));

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        pnlUtama.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlUtama.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        pnlUtama.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        FormInputLapangan formInput = new FormInputLapangan(this, true);
        formInput.setLocationRelativeTo(this);
        formInput.setVisible(true);

        System.out.println("Memuat ulang data tabel...");
        loadDataToTable();
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // 1. Dapatkan nomor baris yang sedang dipilih oleh pengguna di tabel
        int selectedRow = tblLapangan.getSelectedRow();

        // 2. Cek apakah ada baris yang dipilih. getSelectedRow() mengembalikan -1 jika tidak ada.
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris yang ingin dihapus terlebih dahulu.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Hentikan eksekusi
        }

        // 3. Tampilkan dialog konfirmasi untuk memastikan pengguna tidak salah klik
        int confirm = JOptionPane.showConfirmDialog(this,
                "Anda yakin ingin menghapus data ini?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);

        // 4. Cek apakah pengguna mengklik tombol "Yes"
        if (confirm == JOptionPane.YES_OPTION) {
            // 5. Ambil nilai dari kolom pertama (indeks 0), yaitu ID Lapangan, dari baris yang dipilih
            String id = tblLapangan.getValueAt(selectedRow, 0).toString();

            // 6. Panggil controller untuk melakukan penghapusan
            FutsalController controller = new FutsalController();
            boolean sukses = controller.hapusLapangan(id);

            // 7. Beri feedback ke pengguna dan muat ulang tabel
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                loadDataToTable(); // Panggil method ini untuk me-refresh tampilan tabel
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus data.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        int selectedRow = tblLapangan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Silakan pilih baris yang ingin diubah.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil semua data dari baris yang dipilih
        String id = tblLapangan.getValueAt(selectedRow, 0).toString();
        String jenis = tblLapangan.getValueAt(selectedRow, 1).toString();
        String ukuran = tblLapangan.getValueAt(selectedRow, 2).toString();
        double harga = Double.parseDouble(tblLapangan.getValueAt(selectedRow, 3).toString());

        // Buat objek Lapangan dari data tersebut
        Lapangan lapToEdit = new Lapangan(id, jenis, ukuran, harga);

        // Panggil FormInputLapangan menggunakan CONSTRUCTOR KEDUA (untuk mode edit)
        FormInputLapangan formEdit = new FormInputLapangan(this, true, lapToEdit);
        formEdit.setLocationRelativeTo(this);
        formEdit.setVisible(true);

        // Refresh tabel setelah form edit ditutup
        loadDataToTable();
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormManajemenLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormManajemenLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormManajemenLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormManajemenLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormManajemenLapangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tblLapangan;
    // End of variables declaration//GEN-END:variables
}
