/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package manajemen.view;

import java.awt.*;
import javax.swing.*;
import manajemen.controller.FutsalController;  
import manajemen.model.Lapangan; 

/**
 *
 * @author ACER
 */
public class FormInputLapangan extends javax.swing.JDialog {

    private Lapangan lapanganToEdit; 

    /**
     * Creates new form FormInputLapangan1
     */
    public FormInputLapangan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        initializePlaceholders(); 
    }

    // mode EDIT
    public FormInputLapangan(java.awt.Frame parent, boolean modal, Lapangan lapangan) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.lapanganToEdit = lapangan;

        populateForm();
    }
    private void addPlaceholder(JTextField field, String placeholder) {
        if (field.getText().isEmpty()) {
            field.setText(placeholder);
            field.setForeground(Color.GRAY);
        }
    }

    private void removePlaceholder(JTextField field, String placeholder) {
        if (field.getText().equals(placeholder)) {
            field.setText("");
            field.setForeground(Color.BLACK);
        }
    }
    
    private void initializePlaceholders() {
        addPlaceholder(txtIdLapangan, "Contoh: L01");
        addPlaceholder(txtJenis, "Contoh: Rumput Sintetis");
        addPlaceholder(txtUkuran, "Contoh: 25m x 15m");
        addPlaceholder(txtHarga, "Contoh: 150000");
    }
    private void populateForm() {
        txtIdLapangan.setText(lapanganToEdit.getLapanganId());
        txtJenis.setText(lapanganToEdit.getJenisLapangan());
        txtUkuran.setText(lapanganToEdit.getUkuran());
        txtHarga.setText(String.valueOf(lapanganToEdit.getHargaSewaPerJam())); // Konversi double ke String
        
        txtIdLapangan.setForeground(Color.BLACK);
        txtJenis.setForeground(Color.BLACK);
        txtUkuran.setForeground(Color.BLACK);
        txtHarga.setForeground(Color.BLACK);

        txtIdLapangan.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIdLapangan = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtJenis = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUkuran = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Data Lapangan");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID Lapangan");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        txtIdLapangan.setBackground(new java.awt.Color(240, 240, 240));
        txtIdLapangan.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtIdLapangan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdLapanganFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdLapanganFocusLost(evt);
            }
        });
        txtIdLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLapanganActionPerformed(evt);
            }
        });
        jPanel3.add(txtIdLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 170, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Jenis Lapangan");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        txtJenis.setBackground(new java.awt.Color(240, 240, 240));
        txtJenis.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtJenis.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJenisFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJenisFocusLost(evt);
            }
        });
        jPanel3.add(txtJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Ukuran");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Harga Sewa / Jam");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        txtUkuran.setBackground(new java.awt.Color(240, 240, 240));
        txtUkuran.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtUkuran.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUkuranFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUkuranFocusLost(evt);
            }
        });
        jPanel3.add(txtUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 170, -1));

        txtHarga.setBackground(new java.awt.Color(240, 240, 240));
        txtHarga.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtHarga.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHargaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHargaFocusLost(evt);
            }
        });
        jPanel3.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 170, -1));

        btnSimpan.setBackground(new java.awt.Color(153, 227, 62));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel3.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 110, 40));

        btnBatal.setBackground(new java.awt.Color(255, 62, 65));
        btnBatal.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel3.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 110, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("INPUT DATA LAPANGAN");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 430));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLapanganActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String id = txtIdLapangan.getText();
        String jenis = txtJenis.getText();
        String ukuran = txtUkuran.getText();
        String hargaStr = txtHarga.getText();

        if (id.equals("Contoh: L01") || jenis.equals("Contoh: Rumput Sintetis") || 
            ukuran.equals("Contoh: 25m x 15m") || hargaStr.equals("Contoh: 150000") ||
            id.isEmpty() || jenis.isEmpty() || ukuran.isEmpty() || hargaStr.isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi dengan benar!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double harga = Double.parseDouble(hargaStr);
            FutsalController controller = new FutsalController();
            boolean sukses;

            if (lapanganToEdit == null) {
                Lapangan lapBaru = new Lapangan(id, jenis, ukuran, harga);
                sukses = controller.tambahLapangan(lapBaru);
            } else {
                Lapangan lapUpdate = new Lapangan(id, jenis, ukuran, harga);
                sukses = controller.updateLapangan(lapUpdate);
            }

            if (sukses) {
                String message = (lapanganToEdit == null) ? "Data berhasil ditambahkan!" : "Data berhasil diperbarui!";
                JOptionPane.showMessageDialog(this, message);
                this.dispose();
            } else {
                String message = (lapanganToEdit == null) ? "Gagal menambahkan data." : "Gagal memperbarui data.";
                JOptionPane.showMessageDialog(this, message, "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka yang valid!", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdLapanganFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdLapanganFocusGained
        removePlaceholder(txtIdLapangan, "Contoh: L01");
    }//GEN-LAST:event_txtIdLapanganFocusGained

    private void txtIdLapanganFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdLapanganFocusLost
        addPlaceholder(txtIdLapangan, "Contoh: L01");
    }//GEN-LAST:event_txtIdLapanganFocusLost

    private void txtJenisFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJenisFocusGained
        removePlaceholder(txtJenis, "Contoh: Rumput Sintetis");

    }//GEN-LAST:event_txtJenisFocusGained

    private void txtJenisFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJenisFocusLost
        addPlaceholder(txtJenis, "Contoh: Rumput Sintetis");
    }//GEN-LAST:event_txtJenisFocusLost

    private void txtUkuranFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUkuranFocusGained
        removePlaceholder(txtUkuran, "Contoh: 25m x 15m");
    }//GEN-LAST:event_txtUkuranFocusGained

    private void txtUkuranFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUkuranFocusLost
        addPlaceholder(txtUkuran, "Contoh: 25m x 15m");
    }//GEN-LAST:event_txtUkuranFocusLost

    private void txtHargaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHargaFocusGained
        removePlaceholder(txtHarga, "Contoh: 150000");
    }//GEN-LAST:event_txtHargaFocusGained

    private void txtHargaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHargaFocusLost
        addPlaceholder(txtHarga, "Contoh: 150000");
    }//GEN-LAST:event_txtHargaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormInputLapangan dialog = new FormInputLapangan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdLapangan;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtUkuran;
    // End of variables declaration//GEN-END:variables
}
