/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package manajemen.view;
// Jangan lupa tambahkan import ini di bagian atas file

import javax.swing.JOptionPane;
import manajemen.controller.FutsalController; // Mungkin sudah ada
import manajemen.model.Lapangan; // Mungkin sudah ada

/**
 *
 * @author ACER
 */
public class FormInputLapangan extends javax.swing.JDialog {

    private Lapangan lapanganToEdit; // <--- TAMBAHKAN ATRIBUT INI

    /**
     * Creates new form FormInputLapangan1
     */
    public FormInputLapangan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    // Constructor KEDUA untuk mode EDIT
    public FormInputLapangan(java.awt.Frame parent, boolean modal, Lapangan lapangan) {
        super(parent, modal);
        initComponents();

        // Simpan objek lapangan yang akan di-edit
        this.lapanganToEdit = lapangan;

        // Panggil method untuk mengisi form dengan data dari objek
        populateForm();
    }

    // Method untuk mengisi field di form dengan data
    private void populateForm() {
        txtIdLapangan.setText(lapanganToEdit.getLapanganId());
        txtJenis.setText(lapanganToEdit.getJenisLapangan());
        txtUkuran.setText(lapanganToEdit.getUkuran());
        txtHarga.setText(String.valueOf(lapanganToEdit.getHargaSewaPerJam())); // Konversi double ke String

        // PENTING: Buat ID tidak bisa diedit untuk mencegah mengubah Primary Key
        txtIdLapangan.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtIdLapangan = new javax.swing.JTextField();
        txtJenis = new javax.swing.JTextField();
        txtUkuran = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Data Lapangan");

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("ID Lapangan");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, -1, -1));

        jLabel2.setText("Jenis Lapangan");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, -1, -1));

        jLabel3.setText("Ukuran");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, -1, -1));

        jLabel4.setText("Harga Sewa / Jam");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, -1));

        txtIdLapangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLapanganActionPerformed(evt);
            }
        });
        jPanel2.add(txtIdLapangan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 150, -1));
        jPanel2.add(txtJenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 150, -1));
        jPanel2.add(txtUkuran, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 150, -1));
        jPanel2.add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 150, -1));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, -1, -1));

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdLapanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLapanganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLapanganActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // Perintah untuk menutup jendela JDialog ini saja
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // Ambil data dari form (sama seperti sebelumnya)
        String id = txtIdLapangan.getText();
        String jenis = txtJenis.getText();
        String ukuran = txtUkuran.getText();
        String hargaStr = txtHarga.getText();

        if (jenis.isEmpty() || ukuran.isEmpty() || hargaStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua kolom harus diisi!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            double harga = Double.parseDouble(hargaStr);
            FutsalController controller = new FutsalController();
            boolean sukses;

            // Logika PINTAR: Cek apakah ini mode EDIT atau mode TAMBAH
            if (lapanganToEdit == null) { // Jika null, berarti ini mode TAMBAH
                Lapangan lapBaru = new Lapangan(id, jenis, ukuran, harga);
                sukses = controller.tambahLapangan(lapBaru);
            } else { // Jika tidak null, berarti ini mode EDIT
                Lapangan lapUpdate = new Lapangan(id, jenis, ukuran, harga);
                sukses = controller.updateLapangan(lapUpdate);
            }

            if (sukses) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal memperbarui data.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Harga harus berupa angka yang valid!", "Error Input", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputLapangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormInputLapangan dialog = new FormInputLapangan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdLapangan;
    private javax.swing.JTextField txtJenis;
    private javax.swing.JTextField txtUkuran;
    // End of variables declaration//GEN-END:variables
}
