/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package manajemen.view;

import java.awt.Color;
import javax.swing.BorderFactory;
import manajemen.controller.FutsalController;
import manajemen.model.Inventaris;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextArea;
import javax.swing.JTextField; 

/**
 *
 * @author ACER
 */
public class FormInputInventaris extends javax.swing.JDialog {

    // Definisikan variabel warna di tingkat kelas
    final private Color simpanNormal = new Color(153, 227, 62);
    final private Color simpanHover = new Color(90, 140, 30);
    final private Color batalNormal = new Color(255, 62, 65);
    final private Color batalHover = new Color(160, 30, 35);
    // Atribut untuk mode edit
    private Inventaris inventarisToEdit;

    /**
     * Creates new form FormInputPengguna
     */
    public FormInputInventaris(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        initializePlaceholders();
    }

    public FormInputInventaris(java.awt.Frame parent, boolean modal, Inventaris inventaris) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.inventarisToEdit = inventaris;
        populateForm();
    }

    private void addPlaceholder(JTextField field, String placeholder) {
        if (field.getText().isEmpty()) {
            field.setText(placeholder);
            field.setForeground(Color.GRAY);
        }
    }

    private void removePlaceholder(JTextField field, String placeholder) {
        if (field.getText().equals(placeholder)) {
            field.setText("");
            field.setForeground(Color.BLACK);
        }
    }

    private void addPlaceholder(JPasswordField field, String placeholder) {
        char defaultChar = field.getEchoChar();
        if (new String(field.getPassword()).isEmpty()) {
            field.setEchoChar((char) 0); 
            field.setText(placeholder);
            field.setForeground(Color.GRAY);
        }
    }

    private void removePlaceholder(JPasswordField field, String placeholder) {
        char defaultChar = new JPasswordField().getEchoChar(); 
        if (new String(field.getPassword()).equals(placeholder)) {
            field.setText("");
            field.setEchoChar(defaultChar); 
            field.setForeground(Color.BLACK);
        }
    }

    private void initializePlaceholders() {
        addPlaceholder(txtId, "Masukkan ID");
        addPlaceholder(txtNama, "Masukkan Nama Barang");
        addPlaceholder(txtJumlah, "Masukkan Jumlah");
    }
// Method untuk mengisi form saat mode edit

    private void populateForm() {
        txtId.setText(inventarisToEdit.getInventarisId());
        txtNama.setText(inventarisToEdit.getNamaBrg());
        txtJumlah.setText(inventarisToEdit.getJumlah());
        txtId.setForeground(Color.BLACK);
        txtNama.setForeground(Color.BLACK);
        txtJumlah.setForeground(Color.BLACK);

        txtId.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnSimpanUser = new javax.swing.JButton();
        btnBatalUser = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setToolTipText("Form Input Pengguna");
        jPanel1.setMinimumSize(new java.awt.Dimension(420, 420));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(420, 420));
        jPanel2.setPreferredSize(new java.awt.Dimension(420, 420));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        txtId.setBackground(new java.awt.Color(240, 240, 240));
        txtId.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtId.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIdFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdFocusLost(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Nama Barang");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, -1));

        txtNama.setBackground(new java.awt.Color(240, 240, 240));
        txtNama.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtNama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNamaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNamaFocusLost(evt);
            }
        });
        jPanel2.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Jumlah");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        txtJumlah.setBackground(new java.awt.Color(240, 240, 240));
        txtJumlah.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createEmptyBorder(5, 10, 5, 10)));
        txtJumlah.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtJumlahFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtJumlahFocusLost(evt);
            }
        });
        jPanel2.add(txtJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 180, -1));

        btnSimpanUser.setBackground(new java.awt.Color(153, 227, 62));
        btnSimpanUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpanUser.setText("Simpan");
        btnSimpanUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSimpanUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSimpanUserMouseExited(evt);
            }
        });
        btnSimpanUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnSimpanUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, 40));

        btnBatalUser.setBackground(new java.awt.Color(255, 62, 65));
        btnBatalUser.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnBatalUser.setText("Batal");
        btnBatalUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBatalUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBatalUserMouseExited(evt);
            }
        });
        btnBatalUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnBatalUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 110, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setText("INPUT DATA INVENTARIS");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalUserActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalUserActionPerformed

    private void txtIdFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusGained
        removePlaceholder(txtId, "Masukkan ID");
    }//GEN-LAST:event_txtIdFocusGained

    private void txtIdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdFocusLost
        addPlaceholder(txtId, "Masukkan ID");
    }//GEN-LAST:event_txtIdFocusLost

    private void txtNamaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusGained
        removePlaceholder(txtNama, "Masukkan Nama Barang");
    }//GEN-LAST:event_txtNamaFocusGained

    private void txtNamaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNamaFocusLost
        addPlaceholder(txtNama, "Masukkan Nama Barang");
    }//GEN-LAST:event_txtNamaFocusLost

    private void txtJumlahFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahFocusGained
        removePlaceholder(txtJumlah, "Masukkan Jumlah");
    }//GEN-LAST:event_txtJumlahFocusGained

    private void txtJumlahFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtJumlahFocusLost
        addPlaceholder(txtJumlah, "Masukkan Jumlah");
    }//GEN-LAST:event_txtJumlahFocusLost

    private void btnBatalUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalUserMouseEntered
        btnBatalUser.setBackground(batalHover);
    }//GEN-LAST:event_btnBatalUserMouseEntered

    private void btnBatalUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalUserMouseExited
        btnBatalUser.setBackground(batalNormal);
    }//GEN-LAST:event_btnBatalUserMouseExited

    private void btnSimpanUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanUserActionPerformed
        String id = txtId.getText();
        if (id.equals("Masukkan ID")) {
            id = "";
        }
        String namaBrg = txtNama.getText();
        if (namaBrg.equals("Masukkan Nama Barang")) {
            namaBrg = "";
        }
        String jumlah = txtJumlah.getText();
        if (jumlah.equals("Masukkan Jumlah")) {
            jumlah = "";
        }

        if (id.isEmpty() || namaBrg.isEmpty() || jumlah.isEmpty()) {
            JOptionPane.showMessageDialog(this, "ID, Nama Barang, dan Jumlah tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Inventaris inventaris = new Inventaris(id, namaBrg, jumlah);
        FutsalController controller = new FutsalController();
        boolean sukses;

        if (inventarisToEdit == null) {
            System.out.println("Tidak sedang mengedit");
            sukses = controller.tambahInventaris(inventaris);
        } else {
            System.out.println("Sedang mengedit");
            sukses = controller.updateInventaris(inventaris);
        }
        if (sukses) {
            JOptionPane.showMessageDialog(this, "Data inventaris berhasil disimpan!");
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data inventaris.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSimpanUserActionPerformed

    private void btnSimpanUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanUserMouseExited
        btnSimpanUser.setBackground(simpanNormal);
    }//GEN-LAST:event_btnSimpanUserMouseExited

    private void btnSimpanUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanUserMouseEntered
        btnSimpanUser.setBackground(simpanHover);
    }//GEN-LAST:event_btnSimpanUserMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormInputInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormInputInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormInputInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormInputInventaris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormInputInventaris dialog = new FormInputInventaris(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalUser;
    private javax.swing.JButton btnSimpanUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
